title: Ó
description: Frontend thoughs, tips, and memo notebook
author:
  name: Óscar de la Mata
  email: oscardemata@gmail.com
  url: https://katamo.github.io/public-blog/
footer: 
  description: With love for the devs community 
  copyright: Óscar de la Mata - ©2022.
